In [55]:
import Portfolio as port
import pandas
import pandas.io.data
import datetime
import functools

In [56]:
class Backtest:
    Portfolio = None
    Rebalance = None
    Start_Date = None
    End_Date = None
    Asset_Data= None
    
    def __init__(self, cash, assets, start_date, end_date):
        self.Portfolio = port.Portfolio(cash)
        self.Portfolio.AddAssets(assets)
        self.Start_Date = start_date
        self.End_Date = end_date
        self.__download_data(assets, start_date, end_date)

        #self.Asset_Data = pandas.io.data.get_data_yahoo(assets, start = start_date, end = end_date)
        
    def download_data(self, assets, start_date, end_date):
        self.Asset_Data = pandas.io.data.get_data_yahoo(assets, start = start_date, end = end_date)

        
    __download_data = download_data

        
        
        #Rebalance = rebalance_func

In [57]:
MV_BT = Backtest(500, ["SPY"],datetime.datetime(1990, 1,1), datetime.datetime.today())

In [58]:
MV_BT.Asset_Data["Adj Close"]

                  SPY
Date
1993-01-29  28.602132
1993-02-01  28.805561
1993-02-02  28.866558
1993-02-03  29.171734
1993-02-04  29.293791
1993-02-05  29.273416
1993-02-08  29.273416
1993-02-09  29.069987
1993-02-10  29.110673
1993-02-11  29.253106
1993-02-12  29.029301
1993-02-16  28.296956
1993-02-17  28.276646
1993-02-18  28.256271
1993-02-19  28.358017
1993-02-22  28.459700
1993-02-23  28.439389
1993-02-24  28.805561
1993-02-25  28.866558
1993-02-26  28.907244
1993-03-01  28.825872
1993-03-02  29.253106
1993-03-03  29.375163
1993-03-04  29.212420
1993-03-05  29.131048
1993-03-08  29.782021
1993-03-09  29.680274
1993-03-10  29.741335
1993-03-11  29.659964
1993-03-12  29.354788
1993-03-15  29.497220
1993-03-16  29.497220
1993-03-17  29.314102
1993-03-18  29.497220
1993-03-19  29.452549
1993-03-22  29.289037
1993-03-23  29.350386
1993-03-24  29.350386
1993-03-25  29.534305
1993-03-26  29.370793
1993-03-29  29.493427
1993-03-30  29.575183
1993-03-31  29.554776
1993-04-01  29.452549
1993-04-02  28.839379
1993-04-05  28.982485
1993-04-06  28.900729
1993-04-07  29.002891
1993-04-08  28.962013
1993-04-12  29.370793
1993-04-13  29.432142
1993-04-14  29.391264
1993-04-15  29.391264
1993-04-16  29.391264
1993-04-19  29.268630
1993-04-20  29.125525
1993-04-21  29.105119
1993-04-22  28.737217
1993-04-23  28.614583
1993-04-26  28.389722
                  ...

[5775 rows x 1 columns]